-- Vantage — PostgreSQL schema (system of record)
-- =============================================================================
-- Acme Operations, a B2B payments & billing platform. Standard support-ticketing
-- model: customers raise issues; issues accrue an audit trail of updates; admins
-- attach next actions. Five tables per Vantage-vault/04-Architecture.md.
--
-- Contract (track/data → main):
--   * Plain SQL, no application dependencies. Postgres loads this file FIRST,
--     then db/seed.sql, on `docker compose up` (see README "Integration contract").
--   * The seed assigns explicit integer ids and resets identity sequences at the
--     end, so the application can keep inserting without collisions.
--
-- Conventions:
--   * Surrogate keys: BIGINT identity (GENERATED BY DEFAULT so the seed may set
--     ids explicitly; the app omits id and lets Postgres assign it).
--   * Enumerated fields use CHECK constraints (not native ENUM types) so values
--     are visible here in one place and trivially extended without a type migration.
--   * Timestamps are TIMESTAMPTZ; updated_at is application-maintained (no trigger,
--     to keep the schema dependency-free and predictable for the app track).
-- =============================================================================

-- Idempotent (re)create — safe for local dev re-seeding. On a fresh Docker init
-- volume the DROPs are no-ops; on a manual re-run they reset cleanly. Order
-- respects foreign keys (children first); CASCADE covers any leftover deps.
DROP TABLE IF EXISTS next_actions  CASCADE;
DROP TABLE IF EXISTS issue_updates CASCADE;
DROP TABLE IF EXISTS issues        CASCADE;
DROP TABLE IF EXISTS customers     CASCADE;
DROP TABLE IF EXISTS users         CASCADE;

-- -----------------------------------------------------------------------------
-- users — Acme internal staff (our operators), not Acme's customers.
-- `role` MIRRORS Keycloak for attribution / display / seeding ONLY. It is NEVER
-- the live permission check: RBAC reads the verified Keycloak token at the tool
-- boundary (ADR-002). One source of truth for security.
-- `keycloak_id` is the token subject ('sub'); Track A (Keycloak realm) aligns it,
-- or the app joins on `email`, which matches the realm usernames.
-- -----------------------------------------------------------------------------
CREATE TABLE users (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    keycloak_id   TEXT UNIQUE,                      -- Keycloak 'sub'; nullable until realm aligns
    display_name  TEXT        NOT NULL,
    email         TEXT        NOT NULL UNIQUE,
    role          TEXT        NOT NULL
                  CHECK (role IN ('sales_user', 'support_user', 'admin')),
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- -----------------------------------------------------------------------------
-- customers — Acme's customers (online businesses using the payments platform).
-- `account_ref` is the unique, human-facing handle; together with `region` it
-- lets the agent disambiguate near-identical names (edge case E2) instead of
-- silently guessing.
-- -----------------------------------------------------------------------------
CREATE TABLE customers (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                TEXT        NOT NULL,
    account_ref         TEXT        NOT NULL UNIQUE,    -- e.g. 'ACME-10472'
    region              TEXT,                            -- UK region label
    postcode            TEXT,                            -- UK-style postcode
    segment             TEXT  CHECK (segment IN ('SMB', 'Mid-Market', 'Enterprise')),
    tier                TEXT  CHECK (tier    IN ('standard', 'premium', 'strategic')),
    account_manager_id  BIGINT REFERENCES users(id) ON DELETE SET NULL,  -- the sales_user
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- -----------------------------------------------------------------------------
-- issues — support tickets against a customer.
-- "Open" (the get_open_issues tool's filter) = status IN ('open','in_progress','pending').
-- Categories are the payments-platform taxonomy from 04-Architecture (the
-- Escalation Summary Skill reasons over category + priority + age for risk).
-- -----------------------------------------------------------------------------
CREATE TABLE issues (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id  BIGINT      NOT NULL REFERENCES customers(id) ON DELETE CASCADE,
    title        TEXT        NOT NULL,
    description  TEXT        NOT NULL,
    category     TEXT        NOT NULL
                 CHECK (category IN (
                     'integration',            -- webhook / API errors
                     'payments',               -- failed payouts, disputes
                     'onboarding_compliance',  -- KYC / compliance holds
                     'billing',                -- invoice disputes
                     'access',                 -- SSO / API keys
                     'performance'             -- latency / availability
                 )),
    status       TEXT        NOT NULL DEFAULT 'open'
                 CHECK (status IN ('open', 'in_progress', 'pending', 'resolved', 'closed')),
    priority     TEXT        NOT NULL DEFAULT 'medium'
                 CHECK (priority IN ('low', 'medium', 'high', 'critical')),
    assigned_to  BIGINT      REFERENCES users(id) ON DELETE SET NULL,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at   TIMESTAMPTZ NOT NULL DEFAULT now()   -- app-maintained on write
);

-- -----------------------------------------------------------------------------
-- issue_updates — append-only history / audit trail for an issue.
-- This is what summarise_issue_history reads. `update_type` distinguishes a
-- free-text note from a status transition (the body records the transition).
-- -----------------------------------------------------------------------------
CREATE TABLE issue_updates (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    issue_id     BIGINT      NOT NULL REFERENCES issues(id) ON DELETE CASCADE,
    author_id    BIGINT      REFERENCES users(id) ON DELETE SET NULL,  -- attribution
    body         TEXT        NOT NULL,
    update_type  TEXT        NOT NULL DEFAULT 'note'
                 CHECK (update_type IN ('note', 'status_change')),
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- -----------------------------------------------------------------------------
-- next_actions — formal, recorded directives on an issue. Admin-owned: only the
-- `admin` role may create/update them (RBAC enforced at the tool, ADR-002).
-- sales_user receives next actions only as *advice* from the Escalation Summary
-- Skill, which persists nothing.
-- -----------------------------------------------------------------------------
CREATE TABLE next_actions (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    issue_id       BIGINT      NOT NULL REFERENCES issues(id) ON DELETE CASCADE,
    created_by_id  BIGINT      REFERENCES users(id) ON DELETE SET NULL,  -- an admin
    description    TEXT        NOT NULL,
    due_date       DATE,
    status         TEXT        NOT NULL DEFAULT 'open'
                   CHECK (status IN ('open', 'done', 'cancelled')),
    created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at     TIMESTAMPTZ NOT NULL DEFAULT now()   -- app-maintained on write
);

-- -----------------------------------------------------------------------------
-- Indexes — hot query paths (04-Architecture) + every foreign key.
--   * issues.customer_id / issues.status back get_open_issues (per-customer, open).
--   * the *_id FK indexes keep history/next-action joins and cascades cheap.
--   * customers.name supports name lookup + the E1/E2 not-found/ambiguous paths.
-- -----------------------------------------------------------------------------
CREATE INDEX idx_issues_customer_id          ON issues(customer_id);
CREATE INDEX idx_issues_status               ON issues(status);
CREATE INDEX idx_issues_assigned_to          ON issues(assigned_to);
CREATE INDEX idx_issue_updates_issue_id      ON issue_updates(issue_id);
CREATE INDEX idx_issue_updates_author_id     ON issue_updates(author_id);
CREATE INDEX idx_next_actions_issue_id       ON next_actions(issue_id);
CREATE INDEX idx_next_actions_created_by_id  ON next_actions(created_by_id);
CREATE INDEX idx_customers_account_manager_id ON customers(account_manager_id);
CREATE INDEX idx_customers_name              ON customers(name);
